### ISSUE TITLE
Plugin seems to be broken in 3.3.0?

### ISSUE THREAD

**Issue by texnixe** [steirico/kirby-plugin-custom-add-fields#14]
https://forum.getkirby.com/t/the-blueprint-pages-could-not-be-loaded/16323

Just putting the plugin into the plugins folder results in error when trying to add a page in the Panel (without even adding anything to a blueprint).

**Comment by steirico** [comment]
These regressions were introduced in [v1.2.0](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.2.0). Therefore, the error messages are not related to Kirby 3.3.0

[v1.2.1](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.2.1) should fix this.

**Comment by texnixe** [comment]
I suspected that but didn't check. Thanks for fixing that quickly, will test asap.

**Comment by steirico** [comment]
IMHO fixed in [v1.2.1](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.2.1) and newer.
