### ISSUE TITLE
Is it intended that there is no redirect to the page after creating it?

### ISSUE THREAD

**Issue by steirico** [steirico/kirby-plugin-custom-add-fields#17]
As regards redirecting, in my test, I didn't use a hook but created the slug via the `create()` method in a page model…: https://forum.getkirby.com/t/hook-page-create-before-how-to-edit-user-input/12656/5?u=texnixe

_Originally posted by @texnixe in https://github.com/steirico/kirby-plugin-custom-add-fields/issues/10#issuecomment-569830388_

**Comment by texnixe** [comment]
For  pages with little input that can be filled out in the customized form, not redirecting might actually be the desired result. That way, you can easily create one page after the other from the parent page without having to go back. So making the redirect to the page optional via a blueprint setting would actually be my preferred solution.

**Comment by steirico** [comment]
The option is a good idea! And it would work in your use case. I will consider that feature.

But anyway, IMHO the problem remains and is very subtle when hooks are involved.

As you can see [here in the original code of the page create dialog](https://github.com/getkirby/kirby/blob/master/panel/src/components/Dialogs/PageCreateDialog.vue#L127-L132) the redirection happens based on `id` of the backend's response. Due to the presence of [this kirby issue](https://github.com/getkirby/kirby/issues/2377) I'm not aware of any other method for detecting if the slug/id has been changed.

So let's assume that *redirection to the new page is desired* and *that the slug/id has been changed* in a hook. Since the change is not propagated with the response, the panel would redirect using the  ***old / origin*** page `id` of the newly created page. But when the redirection happens the corresponding page doesn't exist and the panel shows up with `The page "xyz" cannot be found`.

**Comment by texnixe** [comment]
Yes, I'm aware of the hook issues, and as long as the hooks don't return anything there is no way to solve this issue, I think.

**Comment by steirico** [comment]
Implemented in [v1.3.0](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.3.0) 😉
