### ISSUE TITLE
"No route found for path"

### ISSUE THREAD

**Issue by nilshoerrmann** [steirico/kirby-plugin-custom-add-fields#28]
After installing this plugin, I get the following error when trying to access the create dialog:

![Bildschirmfoto am 2020-09-23 um 11 00 38](https://user-images.githubusercontent.com/25466/93991964-3e8f0d80-fd8d-11ea-9755-ca9af6face96.png)

```json
{
    "code": 404,
    "details": [],
    "exception": "Exception",
    "file": "/example/kirby/src/Http/Router.php",
    "key": null,
    "line": 154,
    "message": "No route found for path: \"pages/example/blueprints/add-fields\" and request method: \"GET\"",
    "route": null,
    "status": "error"
}
```

It doesn't matter if there are custom add fields or not.
We are using Kirby 3.4.3.

**Comment by nilshoerrmann** [comment]
It seems like the API URL is outdated and it should be:

```
'pattern' => [
    'site/blueprints/add-fields',
    'pages/(:any)/blueprints/add-fields',
],
```

instead of:

```
'pattern' => [
    'site/children/blueprints/add-fields',
    'pages/(:any)/children/blueprints/add-fields',
],
```

**Comment by steirico** [comment]
Thanks for the report and debug effort.

Your are absolutely right. There is a breaking change from Kirby 3.4.2 to 3.4.3 introduced by https://github.com/getkirby/kirby/commit/eac50cc2d90731675e4d8cb0d1b43f111b582e14.

I'll provide the fix asap.

**Comment by nilshoerrmann** [comment]
PR #31 should fix this.
