### ISSUE TITLE
add-dialog broken since 1.4.0

### ISSUE THREAD

**Issue by andreasotto** [steirico/kirby-plugin-custom-add-fields#33]
I've included your plugin as a git submodule and when i switch from 1.3.2 to 1.4.0 the add-dialog is broken: It is empty. 

Tested with kirby version from 3.3.6 up to 3.4.2 

![image](https://user-images.githubusercontent.com/2129515/94345817-eecc7280-0028-11eb-803d-b5be37267425.png)

![image](https://user-images.githubusercontent.com/2129515/94345804-d6f4ee80-0028-11eb-8cb7-3cdb7177b5c7.png)

When i switch back to 1.3.2 everything works again as expected.

![image](https://user-images.githubusercontent.com/2129515/94345832-0b68aa80-0029-11eb-9dce-98ddaa5322ae.png)

![image](https://user-images.githubusercontent.com/2129515/94345845-17ed0300-0029-11eb-8706-14bed26c0e07.png)

I did not change anything in the blueprints.

The add-dialog is empty in every blueprint, it doesn't matter if i have a `addField:` defined or not. Even the standard add dialogs are empty as soon as i switch to 1.4.0.

Please let me know if you need any further information. I'll send them quickly to help to get the issue fixed.

**Comment by steirico** [comment]
I doubt the issue is related to git submodules since I use the plugin in my projects in the same manner.

For kirby v3.4.3 you have to use v1.4.0 of the plugin (c.f. #28)

Does this happen when adding new pages to the site or when adding new pages to an existing page? Could you check these two cases, please?

**Comment by andreasotto** [comment]
Both cases:
- add a new page to the site
- add a new child to a parent page

I just tried it again with Kirby 3.4.3 and kirby-plugin-custom-add-fields 1.4.0 which results in an empty modal dialog like shown above.

**Comment by steirico** [comment]
Could you try if branch [feature/fix-regression](https://github.com/steirico/kirby-plugin-custom-add-fields/tree/feature/fix-regression) fixes the issue?

**Comment by andreasotto** [comment]
Yes, that fixes it for me. The contents of the dialog are there again! ✅

**Comment by steirico** [comment]
@mvilskersts this issue is a regression from #27.

Could you check if the fix in branch [feature/fix-regression](https://github.com/steirico/kirby-plugin-custom-add-fields/tree/feature/fix-regression) still works for your use cases?

**Comment by iskrisis** [comment]
@steirico well for me it fixed redirects actually. They jump to some error page but immediately redirect to proper page. This happens even if i provide title/slug. But better wierd jump than no redirect honestly.

**Comment by mvilskersts** [comment]
@steirico Finally got to using the latest version. 
[feature/fix-regression](https://github.com/steirico/kirby-plugin-custom-add-fields/tree/feature/fix-regression) seems to fix the issue introduced with my PR.
