### ISSUE TITLE
Kirby version 3.4.3 support broken?

### ISSUE THREAD

**Issue by andreasotto** [steirico/kirby-plugin-custom-add-fields#34]
When switching from Kirby 3.4.2 to 3.4.3 (current), clicking on an add-link results in this error:

![image](https://user-images.githubusercontent.com/2129515/94346015-1708a100-002a-11eb-969e-55025ce91acf.png)

Switching back to Kirby version 3.4.2 makes everything work again.

**Comment by steirico** [comment]
See #28 and the release notes for [v1.4.0](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.4.0).
