### ISSUE TITLE
Problem open/preview generated pages from panel

### ISSUE THREAD

**Issue by fendinger** [steirico/kirby-plugin-custom-add-fields#43]
The plugin is storing an empty field called "slug" in the page content-txt-file.

this is causing a problem when open/preview a generated page within the panel by pressing the "Open"-button. The page cannot be opened.

Took a while to figure out that this "slug"-field was the issue ;)

Sample page.txt:

```
Title: Testpage

----

Slug: 

----

...
```

i could handle the problem by adding a line to index.js at line 187:

```
...
        if(pageData.skipDialog){
          data = pageData.page;
        } else {
--->      delete this.page.slug;      <--- added this line
          data = {
            template: this.page.template,
            slug: this.page.slug || Date.now(),
            content: Object.assign({}, this.page)
          };
        }
...
```

after that no more slug-field is added to the content-txt-file.

maybe you want to implement this change?

btw - great plugin! thx!

**Comment by steirico** [comment]
Thanks for your contribution. [v1.4.2](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.4.2) fixes this issue.
