### ISSUE TITLE
Multilanguage problem

### ISSUE THREAD

**Issue by Werbschaft** [steirico/kirby-plugin-custom-add-fields#44]
When using the plgun in a multilanguage way there's a bug. The plugin creates a slug based on the timestamp, but it also creates a field in the txt File with `slug: ` which prevents kirby to work correct.

**Comment by steirico** [comment]
[v1.4.2](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.4.2) fixes this issue.

**Comment by Werbschaft** [comment]
Das does the trick! Thanks 👍
