### ISSUE TITLE
Datepicker is cut off by modal when date-field width is set below 2/3

### ISSUE THREAD

**Issue by hariom147** [steirico/kirby-plugin-custom-add-fields#56]
This seems to be because the date picker is aligned to the end of the field.
`width: 1/2`
![Bildschirmfoto 2021-12-03 um 17 10 21](https://user-images.githubusercontent.com/8297800/144634801-f5d64506-baed-42bc-a93c-82ec4135a166.png)

**Comment by steirico** [comment]
I guess this is related or caused by this [issue](https://github.com/getkirby/kirby/issues/1918). That may be a route you could go for investigating the real cause the problem

**Comment by hariom147** [comment]
I can see, thanks 🙂

**Comment by steirico** [comment]
Not sure if other CSS/plugins might mess something up here.

Using your reported addFields in #55 and changing the `width` of date to `1/3` looks as follow in my setup:

![image](https://user-images.githubusercontent.com/10421363/144710383-a85fde0b-bf51-4954-af34-1d4a493cc763.png)
