### ISSUE TITLE
Redirect does not work when I base page slug on title

### ISSUE THREAD

**Issue by trych** [steirico/kirby-plugin-custom-add-fields#57]
Hi there,

thanks for the useful plugin!

I am trying to redirect the user to the created page, however, I am also having a hook in place, that changes the newly created page's slug to the title:

`site/config/config.php`:
```php
  'hooks' => [
    'page.create:after' => function (Kirby\Cms\Page $page) {
      $page->changeSlug(Str::slug($page->title()->value()));
    }
  ]
```

The redirect still sends me to the default timestamp url of the page though. Is there any easy way to fix this?
Thanks!

**Comment by steirico** [comment]
As mentioned in the [readme](https://github.com/steirico/kirby-plugin-custom-add-fields#configure-redirects) there is a related kirby issue which is [not solvable](https://github.com/getkirby/kirby/issues/2377#issuecomment-586334640).

The only option is to not enable redirection and landing on the parent page.
