### ISSUE TITLE
After creating a page it does not appear

### ISSUE THREAD

**Issue by Werbschaft** [steirico/kirby-plugin-custom-add-fields#59]
We are currently using version 1.5 of the plugin because we cannot yet update to Kirby 3.6. After updating to PHP 8, the following happens:

- we create the page
- but then we have to refresh the panel to see the created page.

Is there a workaround for this?

**Comment by steirico** [comment]
Sorry for the delay. [v1.5.1](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v1.5.1) fixes this issue.
