### ISSUE TITLE
Redirect is disabled on blueprints that do not use addFields

### ISSUE THREAD

**Issue by timkinali** [steirico/kirby-plugin-custom-add-fields#60]
After installing addFields, redirects are disabled everywhere. I didn't it expect to happen on blueprints that do not use addFields. Is it possible to fix this so blueprints without addFields are not affected? If not, perhaps there could be a config option to set desired default?

Of course, I _can_ work around this by setting redirect to true on every individual blueprint:

```
addFields:
  __dialog:
    redirect: true
```

Thank you for a great plugin.

**Comment by steirico** [comment]
Give [3.0.0-beta1](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/3.0.0-beta1) a try, please.

Happy New Year!

**Comment by timkinali** [comment]
Will do, next year 😀 

Happy new year!
