### ISSUE TITLE
Parent page after dialog

### ISSUE THREAD

**Issue by owzim** [steirico/kirby-plugin-custom-add-fields#63]
Version: `2.0.0`
Kirby: `3.7.3`
PHP: `8.0.19`

Just by installing the plugin, without any further settings or configuration, in all instances, when adding a new page anywhere, after the `new dialog` the parent page appears, not the just-created.

**Comment by steirico** [comment]
As mentioned in the [readme](https://github.com/steirico/kirby-plugin-custom-add-fields#configure-redirects) there is a related kirby issue which is [not solvable](https://github.com/getkirby/kirby/issues/2377#issuecomment-586334640).

Therefore, the plugin's default behavior is to remain on the actual panel page after a page has been added.

**Comment by owzim** [comment]
@steirico thanks for pointing that out.

I would be fine with the plugin keeping me on the current page, but it redirects to the **parent** page. So if I have a pages section, which lists children form a certain parent, I will get redirected to that parent, and not stay on the current page. Is this solvable?
