### ISSUE TITLE
Plugin prevents creation of new pages anywhere

### ISSUE THREAD

**Issue by moevbiz** [steirico/kirby-plugin-custom-add-fields#66]
When the plugin is installed, the add dialog stops working and prevents the creation of a new page, no matter if an `addFields` option is present or not. 

Kirby Version: 3.8.3
PHP: 8.0.1
Plugin version: 2.0.0

Tested on a fresh starterkit installation.

<img width="495" alt="Screenshot 2022-12-10 at 16 18 21" src="https://user-images.githubusercontent.com/38008341/206862247-91bf662f-bc6f-4ca7-978a-d0e37bd913b1.png">

**Comment by steirico** [comment]
Thanks for reporting.

There seems to be few [changes](https://github.com/getkirby/kirby/commit/6930ad18ea320131e6da8c19e9eae9bd7ed068d0) in kirby introducing regressions.

I will have a look into this in the next days.

**Comment by steirico** [comment]
Give [3.0.0-beta1](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/3.0.0-beta1) a try, please.

Happy New Year!

**Comment by mbrtltt** [comment]
Running into both this and issue #67 - no apparent difference with 3.0.0-beta1 on my personal site. 
Kirby Version: 3.8.3
PHP: 8.0.26
Plugin version: 3.0.0-beta1
![errors](https://user-images.githubusercontent.com/59071279/210286717-6d541fa2-eade-4e73-a891-8255c3956abd.png)
Also tested in a fresh starterkit installation — curiously, this introduces a new/different error when trying to create a new page:
![dialog](https://user-images.githubusercontent.com/59071279/210286899-c7b4fcd4-4cca-4f7e-bb12-993ec4dfaea1.png)

**Comment by steirico** [comment]
IMHO, kirby 3.8.4 fixed the regression that also broke this plugin.

Please check if [v2.0.0](https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v2.0.0) of the plugin works as expect with kirby 3.8.4.

**Comment by moevbiz** [comment]
seems like it's working now, at least it's not throwing errors on page creation. thank you!
